### PR TITLE
Add moveit config

### PR DESCRIPTION
**Pull request by bhomberg**
(Based on https://github.com/iron-ox/fanuc_experimental/pull/1)

This adds the moveit config for the m20ib.  There's an existing PR to add it to the main repo, but that might not be merged for a bit, so I want this in our repo temporarily (we can overwrite once that's ready).

### CODE REVIEW

**Comment by bhomberg** [comment]
@jonbinney -- if you could also review this one, it would simplify testing of the rosinstall files...

**Review by jonbinney — APPROVED** [review]
@bhomberg approved, but can you remove the whitespace changes in the cpp code before you merge?

**Comment by gavanderhoorn** [comment]
late, but I just noticed that the package name is `fanuc_m20ib_moveit_config`, while it is really a MoveIt configuration for the M-20iB/25, which is a different variant.

**Comment by bhomberg** [comment]
We're actually no longer using this commit any more -- we switched to using a more specific moveit config for our particular robot configuration, including the M-20iB/25, plus our end effector and other specific environmental factors -- we won't be trying to upstream this.

**Comment by gavanderhoorn** [comment]
Just wanted to point out the incorrect name.

:+1: for using a better config :)

**Pull request merged**
